### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by tchaler2017** [skinex/CRUD-SQLite-#1]
i am getting this error.How to solve it? Thanks

root@kali:~/Desktop/CRUD-SQLite-# python main.py
Traceback (most recent call last):
  File "main.py", line 4, in <module>
    from PyQt5 import QtSql
ImportError: cannot import name QtSql

**Comment by skinex** [comment]
Have you installed pyqt5 if not then try installed with this command pip install pyqt5

**Comment by tchaler2017** [comment]
i already have pyqt5. i used
( sudo apt-get install python3-pyqt5
sudo apt-get install python3-pyqt5.qtsql
sudo apt-get install qttools5-dev-tools) 
i am getting error using pip install pyqt5
error : 
pip install pyqt5
Collecting pyqt5
  Could not find a version that satisfies the requirement pyqt5 (from versions: )
No matching distribution found for pyqt5

**Comment by tchaler2017** [comment]
i tried this : pip3 install pyqt5
Requirement already satisfied: pyqt5 in /usr/local/lib/python3.6/dist-packages
Requirement already satisfied: sip<4.20,>=4.19.4 in /usr/local/lib/python3.6/dist-packages (from pyqt5)
but i still have the error : ImportError: cannot import name QtSql

**Comment by tchaler2017** [comment]
i fix it with  apt-get install python-pyqt5.qtsql. it is working now. thanks
